//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cabinet
    {
        public Cabinet()
        {
            this.photo = "/img/cab/cabinet.png";
            this.CabinetService = new HashSet<CabinetService>();
        }
    
        public int idCabinet { get; set; }
        public string nom { get; set; }
        public City ville { get; set; }
        public Nullable<int> code_postale { get; set; }
        public string photo { get; set; }
        public string adresse { get; set; }
        public string description { get; set; }
        public double geoLocationX { get; set; }
        public double geoLocationY { get; set; }
    
        public virtual ICollection<CabinetService> CabinetService { get; set; }
    }
}
