//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICO
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class CabinetService : Personne
    {
        public int Cabinet_idCabinet { get; set; }
    
        public virtual Cabinet Cabinet { get; set; }
    }
}
