//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICO
{
    using System;
    
    public enum City : int
    {
        Casablnca = 1,
        Marrakech = 2,
        Ouarzazate = 3,
        Agadir = 4,
        Rabat = 5,
        Tanger = 6,
        Autre = 0
    }
}
