//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compte
    {
        public Compte()
        {
            this.active = true;
        }
    
        public int idCompte { get; set; }
        public string login { get; set; }
        public string motDePass { get; set; }
        public bool active { get; set; }
        public int Personne_idPersonne { get; set; }
    
        public virtual Personne Personne { get; set; }
    }
}
