//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedicoContext : DbContext
    {
        public MedicoContext()
            : base("name=MedicoContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Personne> Personnes { get; set; }
        public DbSet<Compte> Comptes { get; set; }
        public DbSet<Specialite> Specialites { get; set; }
        public DbSet<RendezVous> RendezVouss { get; set; }
        public DbSet<Cabinet> Cabinets { get; set; }
    }
}
