//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEDICO
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Personne
    {
        public Personne()
        {
            this.telephone = "??";
            this.photo = "/img/avatar.png";
            this.Comptes = new HashSet<Compte>();
        }
    
        public int idPersonne { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string adresse { get; set; }
        public City ville { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string photo { get; set; }
    
        public virtual ICollection<Compte> Comptes { get; set; }
    }
}
